apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: websocket-example
build:
  tagPolicy:
    envTemplate:
      template: "{{.VERSION_SHORT}}-dirty"
  artifacts:
    - image: ghcr.io/public-sysunicorns-info/websocket-api
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs: 
          version: "{{ .VERSION_SHORT }}-dirty"
          version_long: "{{ .VERSION_LONG }}-dirty"
  local:
    useDockerCLI: true
    push: true
deploy:
  helm:
    releases:
      - name: redis
        remoteChart: redis
        namespace: websocket-example
        repo: https://charts.bitnami.com/bitnami
        setValues:
          architecture: standalone
          replica.replicaCount: 0
  kubectl:
    manifests:
      - "k8s/websocket-api/*.yaml"
      - "k8s/redis-commander/*.yaml"
