from pydantic import BaseModel, Field
from datetime import datetime
from enum import Enum

class EventStatus(str, Enum):
    PRISTINE = "PRISTINE"
    ROUTE = "ROUTE"
    SEND = "SEND"
    ACK = "ACK"

class Device(BaseModel):
    device_id: str = Field(title="DeviceId")

class Application(BaseModel):
    name: str = Field(title="Application Name AutoGenerated")
    last_register: datetime = Field(title="Last Register HealthCheck of this application")

class EventForDevice(BaseModel):
    device: Device = Field(title="")
    application: Application = Field(title="")
    payload: str = Field(title="")
    status: EventStatus = Field(title="", default=EventStatus.PRISTINE)
