name: Build and Push Image on Tag
on:
  tags:
    - v1.*
jobs:
  build:
    # Only release on push to master
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # Waits for test jobs for each Node.js version to complete
    # needs: [test]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Github Container Registry
      run: echo $GITHUB_TOKEN | docker login ghcr.io -u USERNAME --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: ${GITHUB_WORKSPACE}/script/docker-build.sh
    - name: Push
      run: ${GITHUB_WORKSPACE}/script/docker-push.sh
