name: "Container Build and Push"

on:
  push:
    branches:
      - "main"
    tags:
      - v1.*
      
jobs:
  image_builder:
    name: Build & Push Container to Github Container Registry
    # Only release on push to master
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # Waits for test jobs for each Node.js version to complete
    # needs: [test]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Github Container Registry
      run: echo $GITHUB_TOKEN | docker login ghcr.io -u miragecentury --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: ${GITHUB_WORKSPACE}/script/docker-build.sh
    - name: Push
      run: ${GITHUB_WORKSPACE}/script/docker-push.sh
