name: "Container Build and Push Test"
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  create:
    tags:
    - "v**"
    push:
      branches:
        - "dev"
jobs:
  image_builder:
    name: Build & Push Container to Github Container Registry
    runs-on: ubuntu-latest
    # Waits for test jobs for each Node.js version to complete
    # needs: [test]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Echo Version
      run:  echo ${GITHUB_TAG}
      env:
        GITHUB_TAG: ${{ steps.get_version.outputs.VERSION }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_REF_TYPE: ${{ github.ref_type }}
        GITHUB_COMMIT_SHA: ${{ github.sha }}
    - name: Echo Python Version Result
      run: python ${GITHUB_WORKSPACE}/src/application/version.py
      env:
        GITHUB_TAG: ${{ steps.get_version.outputs.VERSION }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_REF_TYPE: ${{ github.ref_type }}
        GITHUB_COMMIT_SHA: ${{ github.sha }}
    - name: Login to Github Container Registry
      run: echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: ${GITHUB_WORKSPACE}/script/docker-build.sh
      env:
        GITHUB_TAG: ${{ steps.get_version.outputs.VERSION }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_REF_TYPE: ${{ github.ref_type }}
        GITHUB_COMMIT_SHA: ${{ github.sha }}
    - name: Push
      run: ${GITHUB_WORKSPACE}/script/docker-push.sh
      env:
        GITHUB_TAG: ${{ steps.get_version.outputs.VERSION }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_REF_TYPE: ${{ github.ref_type }}
        GITHUB_COMMIT_SHA: ${{ github.sha }}
