name: Auto Release on Master
on:
  push:
    branches:
      - "main"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 8.1.3
      - name: Install Node Package
        run: npm install
      - name: Run Release Script
        shell: bash
        run: "${GITHUB_WORKSPACE}/script/release.sh"
