name: Auto Release on Master
on:
  push:
    branches:
      - "main"
jobs:
  release:
    # Only release on push to master
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # Waits for test jobs for each Node.js version to complete
    # needs: [test]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Install
      run: npm ci

    - name: Release
      run: ${GITHUB_WORKSPACE}/script/release.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
